//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab5
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="A", Namespace="http://schemas.datacontract.org/2004/07/lab5")]
    public partial class A : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private float fField;
        
        private int kField;
        
        private string sField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float f
        {
            get
            {
                return this.fField;
            }
            set
            {
                this.fField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int k
        {
            get
            {
                return this.kField;
            }
            set
            {
                this.kField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string s
        {
            get
            {
                return this.sField;
            }
            set
            {
                this.sField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IWCFSimplex")]
public interface IWCFSimplex
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSimplex/Add", ReplyAction="http://tempuri.org/IWCFSimplex/AddResponse")]
    int Add(int a, int b);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSimplex/Add", ReplyAction="http://tempuri.org/IWCFSimplex/AddResponse")]
    System.Threading.Tasks.Task<int> AddAsync(int a, int b);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSimplex/Concat", ReplyAction="http://tempuri.org/IWCFSimplex/ConcatResponse")]
    string Concat(string a, double b);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSimplex/Concat", ReplyAction="http://tempuri.org/IWCFSimplex/ConcatResponse")]
    System.Threading.Tasks.Task<string> ConcatAsync(string a, double b);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSimplex/Sum", ReplyAction="http://tempuri.org/IWCFSimplex/SumResponse")]
    lab5.A Sum(lab5.A a, lab5.A b);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSimplex/Sum", ReplyAction="http://tempuri.org/IWCFSimplex/SumResponse")]
    System.Threading.Tasks.Task<lab5.A> SumAsync(lab5.A a, lab5.A b);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IWCFSimplexChannel : IWCFSimplex, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class WCFSimplexClient : System.ServiceModel.ClientBase<IWCFSimplex>, IWCFSimplex
{
    
    public WCFSimplexClient()
    {
    }
    
    public WCFSimplexClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public WCFSimplexClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public WCFSimplexClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public WCFSimplexClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int Add(int a, int b)
    {
        return base.Channel.Add(a, b);
    }
    
    public System.Threading.Tasks.Task<int> AddAsync(int a, int b)
    {
        return base.Channel.AddAsync(a, b);
    }
    
    public string Concat(string a, double b)
    {
        return base.Channel.Concat(a, b);
    }
    
    public System.Threading.Tasks.Task<string> ConcatAsync(string a, double b)
    {
        return base.Channel.ConcatAsync(a, b);
    }
    
    public lab5.A Sum(lab5.A a, lab5.A b)
    {
        return base.Channel.Sum(a, b);
    }
    
    public System.Threading.Tasks.Task<lab5.A> SumAsync(lab5.A a, lab5.A b)
    {
        return base.Channel.SumAsync(a, b);
    }
}
